/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExportMemoRouteImport } from './routes/api/export-memo'
import { Route as ApiDealRouteImport } from './routes/api/deal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportMemoRoute = ApiExportMemoRouteImport.update({
  id: '/api/export-memo',
  path: '/api/export-memo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDealRoute = ApiDealRouteImport.update({
  id: '/api/deal',
  path: '/api/deal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/deal': typeof ApiDealRoute
  '/api/export-memo': typeof ApiExportMemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/deal': typeof ApiDealRoute
  '/api/export-memo': typeof ApiExportMemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/deal': typeof ApiDealRoute
  '/api/export-memo': typeof ApiExportMemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/deal' | '/api/export-memo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/deal' | '/api/export-memo'
  id: '__root__' | '/' | '/api/deal' | '/api/export-memo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDealRoute: typeof ApiDealRoute
  ApiExportMemoRoute: typeof ApiExportMemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-memo': {
      id: '/api/export-memo'
      path: '/api/export-memo'
      fullPath: '/api/export-memo'
      preLoaderRoute: typeof ApiExportMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deal': {
      id: '/api/deal'
      path: '/api/deal'
      fullPath: '/api/deal'
      preLoaderRoute: typeof ApiDealRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDealRoute: ApiDealRoute,
  ApiExportMemoRoute: ApiExportMemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
