/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadOmRouteImport } from './routes/api/upload-om'
import { Route as ApiNegotiationRouteImport } from './routes/api/negotiation'
import { Route as ApiExportMemoRouteImport } from './routes/api/export-memo'
import { Route as ApiDealRouteImport } from './routes/api/deal'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadOmRoute = ApiUploadOmRouteImport.update({
  id: '/api/upload-om',
  path: '/api/upload-om',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNegotiationRoute = ApiNegotiationRouteImport.update({
  id: '/api/negotiation',
  path: '/api/negotiation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportMemoRoute = ApiExportMemoRouteImport.update({
  id: '/api/export-memo',
  path: '/api/export-memo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDealRoute = ApiDealRouteImport.update({
  id: '/api/deal',
  path: '/api/deal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/deal': typeof ApiDealRoute
  '/api/export-memo': typeof ApiExportMemoRoute
  '/api/negotiation': typeof ApiNegotiationRoute
  '/api/upload-om': typeof ApiUploadOmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/deal': typeof ApiDealRoute
  '/api/export-memo': typeof ApiExportMemoRoute
  '/api/negotiation': typeof ApiNegotiationRoute
  '/api/upload-om': typeof ApiUploadOmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/deal': typeof ApiDealRoute
  '/api/export-memo': typeof ApiExportMemoRoute
  '/api/negotiation': typeof ApiNegotiationRoute
  '/api/upload-om': typeof ApiUploadOmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/deal'
    | '/api/export-memo'
    | '/api/negotiation'
    | '/api/upload-om'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/deal'
    | '/api/export-memo'
    | '/api/negotiation'
    | '/api/upload-om'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/deal'
    | '/api/export-memo'
    | '/api/negotiation'
    | '/api/upload-om'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDealRoute: typeof ApiDealRoute
  ApiExportMemoRoute: typeof ApiExportMemoRoute
  ApiNegotiationRoute: typeof ApiNegotiationRoute
  ApiUploadOmRoute: typeof ApiUploadOmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-om': {
      id: '/api/upload-om'
      path: '/api/upload-om'
      fullPath: '/api/upload-om'
      preLoaderRoute: typeof ApiUploadOmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/negotiation': {
      id: '/api/negotiation'
      path: '/api/negotiation'
      fullPath: '/api/negotiation'
      preLoaderRoute: typeof ApiNegotiationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-memo': {
      id: '/api/export-memo'
      path: '/api/export-memo'
      fullPath: '/api/export-memo'
      preLoaderRoute: typeof ApiExportMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deal': {
      id: '/api/deal'
      path: '/api/deal'
      fullPath: '/api/deal'
      preLoaderRoute: typeof ApiDealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDealRoute: ApiDealRoute,
  ApiExportMemoRoute: ApiExportMemoRoute,
  ApiNegotiationRoute: ApiNegotiationRoute,
  ApiUploadOmRoute: ApiUploadOmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
